//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetAllLeaf
    {
        public Nullable<int> id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Approved { get; set; }
        public Nullable<int> LeaveId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEmail { get; set; }
        public string ManagerName { get; set; }
        public string ManagerEmail { get; set; }
        public Nullable<int> GrantedLeaves { get; set; }
        public Nullable<int> AvailedLeaves { get; set; }
    }
}
