//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Leaf()
        {
            this.Leave_Requests = new HashSet<Leave_Requests>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeEmail { get; set; }
        public string ManagerName { get; set; }
        public string ManagerEmail { get; set; }
        public Nullable<int> GrantedLeaves { get; set; }
        public Nullable<int> AvailedLeaves { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leave_Requests> Leave_Requests { get; set; }
    }
}
