//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeaveSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Requests
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Approved { get; set; }
        public Nullable<int> LeaveId { get; set; }
    
        public virtual Leaf Leaf { get; set; }
    }
}
