//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTODOITEM2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TODOItem
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Description is required field.")]
        public string Description { get; set; }
        public string Status { get; set; }
    }
}
