//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIRestResumeAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateResume
    {
        public string CandidateId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public string JobTitle { get; set; }
        public string JobSummary { get; set; }
        public string Education { get; set; }
        public string Projects { get; set; }
        public string Awards { get; set; }
        public string Trainings { get; set; }
        public string Reference { get; set; }
    }
}
